[build-system]
requires = [
    "setuptools>=56",
    "wheel"
]

[project]
name = "fabrication_env"
version = "0.1.0"
dependencies = [
    "fastapi",
    "sqlalchemy",
    "uvicorn",
    "python-multipart",
    "pydantic",
    "httpx"
]
packages = [
    "app"
]
